### ISSUE TITLE
Implementar log com rosbag

### ISSUE THREAD

**Issue by hugotallys** [hugotallys/densoVP6242#3]
Fazer log dos topicos:

- endEffPose (pose)
- position (feedback dos motores)
- targetPosition (sinal de controle)

Criar também um tópico para o clock da simulação (sincronizar tempo do simulador com o no de controle do ROS)

**Comment by glauberrleite** [comment]
Não é necessário realizar o log com rosbag, caso realize os experimentos com action server e salve o feedback em um arquivo csv (dataframe)

**Comment by glauberrleite** [comment]
Já está fazendo com log normal e está funcionando
